name: face-search
channels:
  - conda-forge
  - towhee-io
  - pytorch
dependencies:
  - conda-forge::python=3.10.8
  - conda-forge::pip-autoremove=0.10.0
  - conda-forge::jupyterlab=3.5.0
  - conda-forge::ipywidgets=8.0.3
  - conda-forge::fastapi=0.88.0
  - conda-forge::uvicorn=0.20.0
  - conda-forge::opencv=4.5.5
  - conda-forge::pandas=1.5.2
  - conda-forge::grpcio-tools=1.46.0
  - conda-forge::protobuf=3.20.0
  - conda-forge::onnxruntime=1.13.1
  - conda-forge::scikit-learn=1.1.3
  - conda-forge::black=22.10.0
  - conda-forge::mypy=0.991
  - conda-forge::pylint=2.15.8
  - pytorch::cpuonly=2.0
  - pytorch::pytorch=1.13.0
  - pytorch::torchvision=1.14.0
