name: face-search
channels:
  - conda-forge
  - towhee-io
  - pytorch
dependencies:
  - conda-forge::python=3.10.8
  - conda-forge::pip-autoremove=0.10.0
  - conda-forge::opencv=4.5.5
  - conda-forge::pandas=1.5.2
  - conda-forge::grpcio-tools=1.46.0
  - conda-forge::protobuf=3.20.0
  - conda-forge::onnxruntime=1.13.1
  - conda-forge::scikit-learn=1.1.3
  - pytorch::cpuonly=2.0
  - pytorch::pytorch=1.13.0
  - pytorch::torchvision=1.14.0
